# Generated by Django 6.0.7 on 2026-07-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.CharField(max_length=250, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('category', models.CharField(max_length=50, verbose_name='категория')),
                ('price', models.FloatField(verbose_name='цена за покупку')),
                ('created_at', models.DateTimeField(verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(verbose_name='дата последнего изменения')),
            ],
        ),
    ]
